# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a recipes directory containing .bb and .bbappend files, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
			${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "telechips-nn"
BBFILE_PATTERN_telechips-nn = "^${LAYERDIR}/"
BBFILE_PRIORITY_telechips-nn = "9"

# This should only be incremented on significant changes that will
# cause compatibility issues with other layers
LAYERVERSION_telechips-nn = "2"
LAYERDEPENDS_telechips-nn = "telechips-core telechips-bsp"
LAYERSERIES_COMPAT_telechips-nn = "kirkstone"

NN_PKG_NAME ?= "${@bb.utils.contains('TCC_ARCH_FAMILY', 'tcc750x', '', '', d)}"
NN_VERSION = "TCC750x_Linux_NN_1.0.0"
NN_RELEASE_DATE = "Dec. 14th, 2023"
RM_WORK_EXCLUDE += "${NN_PKG_NAME} telechips-nn-image telechips-nn-image-python telechips-nn-image-minimal"

# do not error out on bbappends for missing recipes
BB_DANGLINGAPPENDS_WARNONLY = "true"

